'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const role=process.argv[2],runId=process.argv[3];
assert(['local','remote'].includes(role),'role must be local or remote');
assert(/^[a-f0-9]{40}$/.test(runId||''),'runId must be full release commit SHA');
assert(process.env.ALLOW_ISOLATED_FIREBASE_TEST==='YES','Explicit isolated test gate required');
const bundle=path.resolve(process.env.BUNDLE_DIR||path.join(__dirname,'candidate'));
const host='menu-plan-f01f7-default-rtdb.firebaseio.com',scope='/menuplan/_verification_sync/'+runId,base='https://'+host+scope;
const weeks=['2026-06-08','2026-06-22','2026-06-29'],result={role,runId,scope,hostname:os.hostname(),platform:process.platform,startedAt:new Date().toISOString(),sourceHashes:{},steps:[],errors:[],blocked:[],socketPaths:[]};
const out=path.resolve(process.env.RESULT_DIR||__dirname,'cross-network-'+role+'.json');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let server,browser,page,active=false;
async function rest(suffix='',method='GET',body){assert(!suffix.includes('..')&&!suffix.includes('?')&&!suffix.includes('#'));const u=base+(suffix?'/'+suffix:'')+'.json';assert(u.startsWith(base+'/')||u===base+'.json');const r=await fetch(u,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(method+' isolated Firebase '+r.status+' '+await r.text());return r.json()}
async function signal(key,value=true){return rest('_verificationControl/'+key,'PUT',value)}
async function awaitControl(key){const end=Date.now()+360000;while(Date.now()<end){const v=await rest('_verificationControl');if(v?.failed)throw Error('Peer failed: '+JSON.stringify(v.failed));if(v?.[key])return v[key];await sleep(750)}throw Error('Peer timeout '+key)}
async function untilServer(fn,label){for(let i=0;i<100;i++){const s=await rest();if(fn(s))return s;await sleep(300)}throw Error('Server timeout '+label)}
function fixture(){const s={start:'2026-06-29',plan:{},confirmed:{},fix:{'김치':{alg:'',slot:'김치'},'흰밥':{alg:'',slot:'밥'}},_ts:{plan:{},confirmed:{},fix:{}},_serverRev:1};for(const w of weeks){const dates=Array.from({length:7},(_,i)=>new Date(Date.parse(w+'T00:00:00Z')+i*86400000).toISOString().slice(0,10)),data={};for(const d of dates){s.plan[d]={};data[d]={};for(const m of ['조식','점심','저녁']){s.plan[d][m]={items:[{n:'흰밥'},{n:'김치'}]};data[d][m]=['흰밥','김치']}}s.confirmed[w]={start:w,dates:dates.slice(0,6),sun:dates[6],data,at:1};s._ts.confirmed[w]=1}return s}
const boot=`(()=>{const scope=${JSON.stringify(scope)};const original=firebase.database;const patched=new WeakSet();function safeDb(db){if(patched.has(db))return db;db.INTERNAL.forceWebSockets();const ref=db.ref.bind(db);db.ref=function(p){p=String(p||'').replace(/^\\//,'');if(p==='.info/connected')return ref(p);if(p!=='menuplan'&&!p.startsWith('menuplan/'))throw Error('Blocked out-of-scope ref '+p);return ref(scope+p.slice(8))};db.refFromURL=function(){throw Error('refFromURL disabled in isolated test')};patched.add(db);return db}function wrapped(...args){return safeDb(original.apply(firebase,args))}Object.assign(wrapped,original);firebase.database=wrapped;const init=firebase.initializeApp.bind(firebase);firebase.initializeApp=function(...args){const app=init(...args),get=app.database.bind(app);app.database=(...x)=>safeDb(get(...x));return app};window.__isolatedScope=scope;})();`;
function instrument(html){html=html.replace(/https:\/\/www\.gstatic\.com\/firebasejs\/10\.12\.2\/(firebase-(?:app|database)-compat\.js)/g,(_,n)=>'/sdk/'+n);return html.replace(/<script\b[^>]*src="\/sdk\/firebase-database-compat\.js"[^>]*><\/script>/g,t=>t+'<script src="/sdk/isolate.js"></script>')}
async function start(){const sdk={};for(const n of ['firebase-app-compat.js','firebase-database-compat.js']){const local=path.resolve(__dirname,'../bareun-sdk-verification-20260914/sdk',n);if(role==='local'&&fs.existsSync(local))sdk[n]=fs.readFileSync(local);else{const r=await fetch('https://www.gstatic.com/firebasejs/10.12.2/'+n);assert(r.ok);sdk[n]=Buffer.from(await r.arrayBuffer())}}
 const files={};for(const n of ['menu-plan.html','mobile-memo.html','bareun-backup-archive.js','bareun-backup-runtime.js','bareun-operation-journal.js']){files[n]=fs.readFileSync(path.join(bundle,n),'utf8');result.sourceHashes[n]=crypto.createHash('sha256').update(files[n]).digest('hex')}
 server=http.createServer((req,res)=>{const n=new URL(req.url,'http://localhost').pathname.slice(1);res.setHeader('Cache-Control','no-store');if(req.method!=='GET'){res.writeHead(405);return res.end()}if(n==='sdk/isolate.js'){res.setHeader('Content-Type','application/javascript');return res.end(boot)}if(n.startsWith('sdk/')&&sdk[n.slice(4)]){res.setHeader('Content-Type','application/javascript');return res.end(sdk[n.slice(4)])}if(!Object.hasOwn(files,n)){res.writeHead(404);return res.end()}res.setHeader('Content-Type',n.endsWith('.js')?'application/javascript':'text/html; charset=utf-8');let html=files[n];if(n==='menu-plan.html'){const tag='<script id="bareun-order-srcdoc" type="application/json">',i=html.indexOf(tag)+tag.length,j=html.indexOf('</script>',i);assert(i>=tag.length&&j>i);html=html.slice(0,i)+JSON.stringify(instrument(JSON.parse(html.slice(i,j)))).replace(/<\//g,'<\\/')+html.slice(j)}res.end(n.endsWith('.html')?instrument(html):html)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
 const playwright=require(role==='local'?'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright':'playwright');browser=await playwright.chromium.launch({headless:true,...(role==='local'?{executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}:{})});const context=await browser.newContext({serviceWorkers:'block',viewport:role==='local'?{width:1440,height:1000}:{width:390,height:844}});context.setDefaultTimeout(25000);
 await context.route('**/*',r=>{if(new URL(r.request().url()).origin===origin)return r.continue();result.blocked.push(r.request().url());return r.abort()});
 await context.routeWebSocket('**/*',ws=>{const u=new URL(ws.url());if(u.hostname!==host||u.protocol!=='wss:'){result.errors.push('Blocked socket host '+u.hostname);return ws.close()}const upstream=ws.connectToServer();ws.onMessage(message=>{try{const msg=JSON.parse(String(message));if(msg.t==='d'){const a=msg.d?.a,p=msg.d?.b?.p;if(typeof p==='string'){const normalized='/'+p.replace(/^\//,'');if(!(normalized===scope||normalized.startsWith(scope+'/')||(normalized==='/.info/connected'&&['q','n'].includes(a))))throw Error('Blocked Firebase path '+normalized);result.socketPaths.push({action:a,path:normalized})}else if(['p','m','q','n','o'].includes(a))throw Error('Missing Firebase path '+a)}upstream.send(message)}catch(e){result.errors.push(e.message);ws.close()}});upstream.onMessage(m=>ws.send(m))});
 page=await context.newPage();page.on('pageerror',e=>result.errors.push(e.message));page.on('dialog',d=>d.accept());return {origin,context}}
const sel=w=>`.cfbtn[onclick="confirmWeek('${w}')"]`;
async function loaded(origin){await page.goto(origin+'/menu-plan.html?start=2026-06-29');await page.waitForFunction(()=>typeof fbReady!=='undefined'&&fbReady&&sharedJournalReady);await page.waitForFunction(()=>document.querySelector('.cfbtn[onclick="confirmWeek(\'2026-06-29\')"]'));assert.equal(await page.evaluate(()=>window.__isolatedScope),scope)}
async function shown(w,on){await page.waitForFunction(({w,on})=>document.querySelector('.cfbtn[onclick="confirmWeek(\''+w+'\')"]')?.classList.contains('done')===on,{w,on})}
async function otherWeeks(){await shown('2026-06-22',true);const keys=await page.evaluate(()=>Object.keys(S.confirmed||{}));assert(keys.includes('2026-06-08'));assert(keys.includes('2026-06-22'))}
async function allergy(num){await page.locator('.cell[data-date="2026-06-29"][data-meal="조식"]').click();const idx=await page.evaluate(()=>S.plan[cur.date][cur.meal].items.findIndex(x=>x.n==='김치'));assert(idx>=0);await page.locator(`[onclick="toggleAlgEdit(${idx})"]`).click();await page.locator(`[onclick="toggleAlg(${idx},${num})"]`).click()}
async function observeAlg(value){await page.waitForFunction(v=>String(S.fix?.['김치']?.alg||'')===v,value)}
function passed(name,extra={}){result.steps.push({name,pass:true,at:new Date().toISOString(),...extra});console.log(role+': '+name)}
(async()=>{try{
 if(role==='local'){assert.equal(await rest(),null,'Unique synthetic run must not already exist');await rest('','PUT',fixture());active=true}else{await awaitControl('localReady');active=true}
 const {origin,context}=await start();await loaded(origin);await otherWeeks();await shown('2026-06-29',true);passed('Synthetic weeks loaded via real Firebase SDK');
 if(role==='local'){
  await signal('localReady',{hash:result.sourceHashes['menu-plan.html'],host:os.hostname()});const peer=await awaitControl('remoteReady');assert.equal(peer.hash,result.sourceHashes['menu-plan.html']);assert.notEqual(peer.host,os.hostname());result.peer=peer;
  await page.locator(sel('2026-06-29')).click();const s=await untilServer(v=>!v.confirmed?.['2026-06-29'],'local cancellation');assert.deepEqual(Object.keys(s.confirmed).sort(),weeks.slice(0,2));passed('Local actual click reached Firebase; only June29 removed');await signal('cancelWritten');
  await awaitControl('remoteConfirmed');await shown('2026-06-29',true);await otherWeeks();passed('Remote actual confirmation received automatically by local');await page.reload();await page.waitForFunction(()=>typeof fbReady!=='undefined'&&fbReady);await shown('2026-06-29',true);passed('Local reload preserved remote confirmation');
  await allergy(1);await untilServer(v=>v.fix?.['김치']?.alg==='1','local allergy');await signal('localAllergyWritten');await awaitControl('remoteAllergyWritten');
  // Close the local editor through its existing close control so deferred remote updates can apply.
  const close=page.locator('#sheet .shh .x');if(await close.count())await close.first().click();else await page.keyboard.press('Escape');
  await observeAlg('1.5');await otherWeeks();passed('Remote allergy edit automatically received by local');await signal('localFinished');await awaitControl('remoteFinished');
 }else{
  const peer=await rest('_verificationControl/localReady');assert.equal(peer.hash,result.sourceHashes['menu-plan.html']);result.peer=peer;await signal('remoteReady',{hash:result.sourceHashes['menu-plan.html'],host:os.hostname()});
  await awaitControl('cancelWritten');await shown('2026-06-29',false);await otherWeeks();passed('Local cancellation automatically received on GitHub network; other weeks retained');
  await page.locator(sel('2026-06-29')).click();await untilServer(v=>!!v.confirmed?.['2026-06-29'],'remote confirmation');passed('Remote actual confirmation click reached Firebase');await signal('remoteConfirmed');
  await awaitControl('localAllergyWritten');await observeAlg('1');await otherWeeks();passed('Local allergy edit automatically received by remote');await allergy(5);await untilServer(v=>v.fix?.['김치']?.alg==='1.5','remote allergy');await signal('remoteAllergyWritten');await awaitControl('localFinished');
  await page.reload();await page.waitForFunction(()=>typeof fbReady!=='undefined'&&fbReady);await observeAlg('1.5');await shown('2026-06-29',true);await otherWeeks();passed('Remote reload retained shared allergy and confirmation');
  const mobile=await context.newPage();mobile.on('pageerror',e=>result.errors.push(e.message));await mobile.clock.setFixedTime(new Date('2026-06-29T03:00:00Z'));await mobile.goto(origin+'/mobile-memo.html');await mobile.waitForFunction(()=>document.querySelector('#conn')?.textContent==='실시간 연결됨');const text=await mobile.locator('body').innerText();assert(text.includes('김치')&&text.includes('흰밥'));passed('Mobile memo real SDK received synthetic June29 menu');await signal('remoteFinished');
 }
 assert.equal(result.errors.length,0,JSON.stringify(result.errors));result.pass=true;
 }catch(e){result.pass=false;result.failure=e.stack;console.error(e.stack);try{if(active)await signal('failed',{role,message:e.message})}catch{}process.exitCode=1}finally{result.finishedAt=new Date().toISOString();if(page)try{result.body=(await page.locator('body').innerText()).slice(0,10000)}catch{}if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(result,null,2))}})();
